[package]
name = "omni"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
clap = { version = "4.5.54", features = ["derive"] }
tokio = { version = "1.49.0", features = ["full"] }
btleplug = "0.11"
uuid = "1.0"
futures = "0.3"
prost = "0.13"
ring = "0.17"
rand = "0.8"
hex = "0.4"

[build-dependencies]
prost-build = "0.13"
